name: Inspiration
favicon: null
layout_spectrum: 0.8
purposes:
  - followers
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4e4a49'
    - '#040203'
    - '#9d7a64'
    - '#292524'
    - '#ccb09b'
  brandStrength: 1
  lightness: 0.125
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
